### ISSUE TITLE
google spreadsheet mapping formula not working

### ISSUE THREAD

**Issue by xotla** [okfn/timemapper#180]
On the google spreadsheet template there is a map formula that no longer works. The link doesn't go anywhere.  I believe it has something to do with this message on the Mapquest developer page, "All Nominatim and Xapi requests require a key starting September 15, 2015. Please visit the MapQuest Developer Network to sign up for an AppKey if you do not have one."  This is a message on this page: http://open.mapquestapi.com/nominatim/  
I know next to nothing about coding/software so if anyone here has ideas about how to fix this it would be awesome! Thank you.

**Comment by danfowler** [comment]
Thanks @xotla, this has now been fixed: https://github.com/okfn/timemapper/issues/182#issuecomment-169689212
