### ISSUE TITLE
issue with place automatic completion 

### ISSUE THREAD

**Issue by ivandps** [okfn/timemapper#182]
it seems this code in spreadsheet does not function anymore... 

=JOIN(",", ImportXML(CONCATENATE("http://open.mapquestapi.com/nominatim/v1/search?format=xml&q=",F3), "//place[1]/@lat | //place[1]/@lon"))

**Comment by danfowler** [comment]
Hi @ivandps, you might consider this version of the API which has a [different usage policy](http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy) and no requirement for an API key: http://wiki.openstreetmap.org/wiki/Nominatim



For more info on why the code doesn't function anymore: http://devblog.mapquest.com/2015/08/17/mapquest-free-open-license-updates-and-changes/

**Comment by Kent-Gerber** [comment]
@ivandps and @danfowler I used the Nominatim wiki to reconfigure the API in the spreadsheet and it works now - 
=JOIN(",", ImportXML(CONCATENATE("**http://nominatim.openstreetmap.org/search/?format=xml&q="**,J2), "//place[1]/@lat | //place[1]/@lon"))

**Comment by danfowler** [comment]
Thanks so much @Kent-Gerber!  I've updated the [example spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Al6mO9_3Hr2PdGZnRjEwUWxOekhreTNNZEFEMWRZbkE) with the updated API call.
