### ISSUE TITLE
geocoder link doesn't work anymore for http://timemapper.okfnlabs.org 

### ISSUE THREAD

**Issue by cirospat** [okfn/timemapper#183]
on  http://timemapper.okfnlabs.org 
there is a db sample = https://docs.google.com/spreadsheets/d/1LlYBnfhvD3ZUXMGZ8e52UwYp-xn_NeWmaGBx7VBz5V8/edit#gid=0
and
on K3 cell there is a link for geocoder = http://open.mapquestapi.com/nominatim/v1/search?format=xml&q= 
this link doesn't work and gives error in city lat and long geographical data;
correct link now is = http://nominatim.openstreetmap.org/search?format=xml&q=

DB sample K coloumn need to be corrected with right link for geocoder

**Comment by danfowler** [comment]
Thanks, corrected.
