### ISSUE TITLE
Javascript error on embed

### ISSUE THREAD

**Issue by codegliders** [okfn/timemapper#198]
If you try to open the embed window you get some errors in console:
In leaflet label you get: this._update() is not a function
In view.js you get $(...).modal is not a function

Any suggestions?

**Comment by codegliders** [comment]
Found a fix fir In view.js you get $(...).modal is not a function
In timemap.html change bootstrap version 2.0.2 with 2.3.2 since in leaflet current version there is no 2.0.2 bootstrap version, while there is 2.3.2

**Comment by danfowler** [comment]
Thanks.  This is fixed.  I actually linked to the 2.2.2 version on the CDN to match the version of Bootstrap CSS currently in use.   Sorry for the delay!
