### ISSUE TITLE
Examples Not Loading

### ISSUE THREAD

**Issue by scurryjohnson** [okfn/timemapper#225]
Hi, multiple attempts by multiple users have been unable to load the examples on the main page.  These would greatly help students to decide on how this program works.

**Comment by Tang-L11** [comment]
It looks like that the server has been down for at least two months. Could you please solve this issue at your earliest convenience? Thank you very much!

**Comment by thtbln** [comment]
Some of the timemaps I created (http://timemapper.okfnlabs.org/thtbln) are loading again, some are loading for several minutes but don't show.

**Comment by amercader** [comment]
See https://github.com/okfn/timemapper/issues/224#issuecomment-932108304 for the latest update on this

**Comment by aivuk** [comment]
Hi @thtbln, I pushed a new update to the server and now all your timemaps are workin again. All the examples are also working again after the update.

**Comment by thtbln** [comment]
Thanks a lot.
However the following data seem not to be processed anymore (cf. [Das erste Jahrtausend](http://timemapper.okfnlabs.org/thtbln/das-erste-jahrtausend-im-vorderen-orient#30)):
1. Web Page: used to be the link for Title
2. Media Credit: used to be placed under the Media (with URL shown as link)
3. Media Caption: used to be placed under the Media Credit
4. Source URL: used to be the link for Source (not in the screenshot)

![timemapper_1000_30](https://user-images.githubusercontent.com/5794605/142001000-7bd1845f-9280-4409-9660-dbd50896d7bd.png)

**Comment by Tang-L11** [comment]
Yes, Yes, I'm experiencing the same issues with my timemaps: https://timemapper.okfnlabs.org/usceastasianli1/warlord-era, https://timemapper.okfnlabs.org/usceastasianli1/nanjing-decade, https://timemapper.okfnlabs.org/usceastasianli1/sino-japanese-war, and https://timemapper.okfnlabs.org/usceastasianli1/chinese-civil-war. Particularly, these timemaps will become useless if the items cannot be linked to the original collection website.

**Comment by aivuk** [comment]
@thtbln and @Tang-L11 thanks for reporting it! I investigated the reported problem and I found out a solution. Please check again your Timemaps and tell us if there is something still missing.

**Comment by Tang-L11** [comment]
Thank you @aivuk so much for fixing this problem so quickly! All my timemaps are now working perfectly on my end.

**Comment by thtbln** [comment]
Thanks a lot for the quick solution. In your hands @aivuk Timemapper seems to have a promising future:
![casablanca](https://user-images.githubusercontent.com/5794605/142178552-c727756a-9f7d-423c-b651-dffe917360da.png)
.
